[package]
name = "firm-wallet-gateway"
authors = ["Haoran.Xuan@airwallex.com"]
version = "0.1.0"
edition = "2018"

[[bin]]
name = "firm-wallet-gateway"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hologram_protos ={ version = "0.1.0", path ="../dependencies/hologram-protos"}
gateway_framework ={ version = "0.1.0", path = "../dependencies/infra-common/gateway_framework"}

# tokio async tool
tokio = { version = "1.17", features = ["rt", "macros", "rt-multi-thread"] }
async-trait = "0.1"

# tonic grpc client & server
tonic = { version = "0.5.2", features = ["tls"] }
tower = "0.4.7"
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }

# tools
dotenv = "0.15.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hmac = "0.12.1"
sha2 = "0.10.6"
subtle = "2.4.1"

# logging
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
rusty-hook = "^0.11.2"
